// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID         uuid.UUID
	Url        string
	Name       string
	Logo       sql.NullString
	CategoryID uuid.UUID
	UserID     uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Category struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserAccount struct {
	ID        uuid.UUID
	Email     string
	PwdHash   string
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
